### PR TITLE
Akhundov Ruslan 2537

### PR DESCRIPTION
**Pull request by korektur**

### CODE REVIEW

**Comment by thevery** [comment]
details screen should open details, not link as text

**Comment by korektur** [comment]
It was fixed on the lesson, But i didnt pushed because i instantly showed it to another teacher, i think we forgot to close this repository

**Comment by thevery** [comment]
list should show titles, not content

**Comment by thevery** [comment]
parser is broken for bash.im

**Comment by thevery** [comment]
anyway, you've already got your points :(

**Pull request closed without merging**
